<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_medicahmsgmail.com</name>
   <tag></tag>
   <elementGuidId>b08c1416-0e6c-4ce0-8dbe-9763e0a8c779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'medicahms@gmail.com')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16c7cada-a706-4587-8b04-438715d13579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:medicahms@gmail.com</value>
      <webElementGuid>73b65c7b-5415-4f25-9df2-92d8693d949e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>medicahms@gmail.com
                    </value>
      <webElementGuid>bbbc2a4b-2035-44d8-9107-dfca75befe2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;form-container&quot;]/form[1]/a[2]</value>
      <webElementGuid>46366f40-7340-46e5-a0e6-eb0400be8264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'medicahms@gmail.com')]</value>
      <webElementGuid>f52e2c03-6e95-4b43-b5d6-0049bf239864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:medicahms@gmail.com')]</value>
      <webElementGuid>731314ce-fe49-45bc-9112-7a20405389e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>7d5acbc7-0107-478a-a1c3-b8abf3de2ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:medicahms@gmail.com' and (text() = 'medicahms@gmail.com
                    ' or . = 'medicahms@gmail.com
                    ')]</value>
      <webElementGuid>a3b8f076-a6d1-4563-a98b-f00933780e82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
