<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-edit</name>
   <tag></tag>
   <elementGuidId>a8261f44-13e6-4adf-a5e5-535cff84950d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='reference_2']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9e135900-fb47-40a4-95e7-470d974cfad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit</value>
      <webElementGuid>cf12d5dd-92c2-4e28-b6c7-318388b030d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>293fef95-0a50-43ab-ac63-dd39133dc490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference_2&quot;)/i[@class=&quot;fa fa-edit&quot;]</value>
      <webElementGuid>e9b20bd3-b1a9-48b7-9b74-005b6c0da266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='reference_2']/i</value>
      <webElementGuid>c6ffd765-2496-4b14-a26a-db6b825a6764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>3041f6b1-bf56-495c-a010-b0cd3d966095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Edit']</value>
      <webElementGuid>edfc3d16-a913-49af-be61-0e2f7fb646f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
