<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_full_name</name>
   <tag></tag>
   <elementGuidId>5f715f03-0927-4277-9346-656690d26a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#full_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='full_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cdce0bb-760c-48b6-bf2d-cecb85965c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3297850-19a1-46b0-a974-bbce564103b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f71cd809-6aaa-401c-9588-4ea2a078aa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>af726dcf-c293-4918-ae19-88ee7764c38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>40043530-0ab1-4619-aa71-3d7d77b3181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your Full Name</value>
      <webElementGuid>16745f64-4f99-403b-b9c2-607362f5b29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full_name&quot;)</value>
      <webElementGuid>d1b8a57c-239f-4fea-89be-3719797ae74c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='full_name']</value>
      <webElementGuid>1348fc53-6eaf-4a71-a610-82c0f267c077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-0']/div/div/div/input</value>
      <webElementGuid>e79324e6-ed01-4f7d-a801-822579becc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e17a2e29-83b9-4485-8e07-55f695c5356a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'full_name' and @id = 'full_name' and @placeholder = 'Write your Full Name']</value>
      <webElementGuid>f98cf9d8-55ff-4ed6-b82a-bf1f24797fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
