<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select Patient Blood GroupABA_6d419e</name>
   <tag></tag>
   <elementGuidId>104594dc-ccb8-4b09-a2ac-1469fdef0851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;blood_group&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='blood_group']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b5467ed-ff5d-4545-84cb-20dbd9f41eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>37c9883d-5a12-4505-a00e-6465c77cb279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>blood_group</value>
      <webElementGuid>d1471705-93fe-4c58-bb8e-4522807d4b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Patient Blood GroupA+B+AB+AB-O+O-A-B-</value>
      <webElementGuid>aa4ea26b-ad1a-45e8-8249-4e77b127ae25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-step-1&quot;)/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-8&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5363bb4f-6233-4893-9b01-f95e01407bf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='blood_group']</value>
      <webElementGuid>dd87488c-300e-4e0a-b87d-657bade09e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-1']/div/div/div/select</value>
      <webElementGuid>a9c5c179-e82a-4d32-8623-1a15f4fc057e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/select</value>
      <webElementGuid>66bec71d-2ee8-467c-b51a-3f558533852d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'blood_group' and (text() = 'Please Select Patient Blood GroupA+B+AB+AB-O+O-A-B-' or . = 'Please Select Patient Blood GroupA+B+AB+AB-O+O-A-B-')]</value>
      <webElementGuid>4f2fccf6-d5ca-4bcf-95eb-efe30b2c7ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
